#!/bin/bash

echo "MDT数据库初始化脚本"
echo "===================="
echo ""
echo "请确保MySQL服务已启动，然后执行以下命令："
echo ""
echo "1. 创建数据库结构："
echo "   mysql -u root < src/database/schema.sql"
echo ""
echo "2. 导入测试数据："
echo "   mysql -u root mdt < src/database/seed.sql"
echo ""
echo "如果MySQL需要密码，请添加 -p 参数"
echo ""
echo "===================="
echo ""
echo "你也可以手动执行："
echo "1. 登录MySQL: mysql -u root"
echo "2. 执行: source src/database/schema.sql"
echo "3. 执行: source src/database/seed.sql"